- 👋 Hi, I’m S.Naveen
- 👀 I’m interested in embedded project and making website...
- 🌱 I’m currently learning PLC and VLSI...
- 💞️ I’m looking for a semiconductor company and plc company jobs ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
NaveenS2003/NaveenS2003 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
